// cypress.config.js

const { defineConfig } = require("cypress");
const { GoogleGenerativeAI } = require("@google/generative-ai");
const fs = require("fs");
const path = require("path");
require('dotenv').config({ path: 'D:/Git/.env' }); // PC
//require('dotenv').config({ path: 'D:/Git/.env' }); // Laptop

// Validate API key
if (!process.env.API_KEY) {
    throw new Error("Missing API Key. Please check your .env file or ENV_PATH.");
}
module.exports = defineConfig({
    e2e: {
        retries: {
            runMode: 1, //Headless
            openMode: 1 //GUI
        },
        setupNodeEvents(on, config) {
            on('task', {
                generateContent({ baseImage, manipulatedImage, prompt }) {
                    const genAI = new GoogleGenerativeAI(process.env.API_KEY);
                    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

                    const images = [
                        {
                            inlineData: {
                                data: baseImage.data,
                                mimeType: baseImage.mimeType
                            }
                        },
                        {
                            inlineData: {
                                data: manipulatedImage.data,
                                mimeType: manipulatedImage.mimeType
                            }
                        }
                    ];

                    return model.generateContent([images, prompt])
                        .then((result) => {

                            if (!result) {
                                throw new Error('Task failed: No content generated by the model.');
                            }

                            const text = result.response.text();
                            const dirPath = 'cypress/outputs';

                            try {
                                //Path validation
                                if (!fs.existsSync(dirPath)) {
                                    fs.mkdirSync(dirPath);
                                }

                                fs.writeFileSync(`${dirPath}/GeminiOutput.txt`, text, { flag: 'w' });
                                return text; // Return the result to Cypress for further use
                            }
                            catch (fileError) {
                                console.error('Error handling output file:', fileError.message);
                                throw new Error('Failed to write generated content to output file.');
                            }
                        })
                        .catch((error) => {
                            console.error("Error generating content:", error);
                            throw error;
                        });
                }
            });
            on('after:screenshot', (details) => {
                if (details.testFailure) { // Only for failed tests
                    const now = new Date();
                    const formattedDate = `${now.getFullYear()}-${(now.getMonth() + 1).toString().padStart(2, '0')}-${now.getDate().toString().padStart(2, '0')}`;
                    const formattedTime = `${now.getHours().toString().padStart(2, '0')}-${now.getMinutes().toString().padStart(2, '0')}-${now.getSeconds().toString().padStart(2, '0')}`;

                    // Create a new filename with the date and time
                    const filePath = details.path;
                    const dirname = path.dirname(filePath);
                    const extname = path.extname(filePath);
                    const basename = path.basename(filePath, extname);
                    const newFileName = `${basename}_${formattedDate}_${formattedTime}${extname}`;
                    const newFilePath = path.join(dirname, newFileName);

                    try {
                        // Ensure the directory exists
                        if (!fs.existsSync(dirname)) {
                            fs.mkdirSync(dirname, { recursive: true });
                        }

                        // Rename the screenshot file
                        fs.renameSync(filePath, newFilePath);

                        // Return updated details to Cypress
                        return {
                            ...details,
                            path: newFilePath,
                        };
                    } catch (error) {
                        console.error('Error renaming screenshot:', error.message);
                        // Optional: You can throw an error here if you want to fail the test entirely
                    }
                }

                // Return unchanged details for non-failed screenshots
                return details;
            });

        },

        supportFile: 'cypress/support/commands.js',
    },
});
