// cypress.config.js

const { defineConfig } = require("cypress");
const { GoogleGenerativeAI } = require("@google/generative-ai");
const fs = require("fs");
require('dotenv').config({ path: 'D:/Git/.env' }); // PC
//require('dotenv').config({ path: 'D:/Git/.env' }); // Laptop

// Validate API key
if (!process.env.API_KEY) {
    throw new Error("Missing API Key. Please check your .env file or ENV_PATH.");
}
module.exports = defineConfig({
    e2e: {
        retries: {
            runMode: 2,
            openMode: 1
        },
        setupNodeEvents(on, config) {
            on('task', {
                generateContent({ baseImage, manipulatedImage, prompt }) {
                    const genAI = new GoogleGenerativeAI(process.env.API_KEY);
                    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

                    const images = [
                        {
                            inlineData: {
                                data: baseImage.data,
                                mimeType: baseImage.mimeType
                            }
                        },
                        {
                            inlineData: {
                                data: manipulatedImage.data,
                                mimeType: manipulatedImage.mimeType
                            }
                        }
                    ];

                    return model.generateContent([images, prompt])
                        .then((result) => {

                            if (!result) {
                                throw new Error('Task failed: No content generated by the model.');
                            }

                            const text = result.response.text();
                            const dirPath = 'cypress/outputs';

                            try {
                                //Path validation
                                if (!fs.existsSync(dirPath)) {
                                    fs.mkdirSync(dirPath);
                                }

                                fs.writeFileSync(`${dirPath}/GeminiOutput.txt`, text, { flag: 'w' });
                                return text; // Return the result to Cypress for further use
                            }
                            catch (fileError) {
                                console.error('Error handling output file:', fileError.message);
                                throw new Error('Failed to write generated content to output file.');
                            }
                        })
                        .catch((error) => {
                            console.error("Error generating content:", error);
                            throw error;
                        });
                }
            });
        },
        supportFile: 'cypress/support/commands.js',
    },
});
//retry with timeout

